# Generated by Django 5.0.2 on 2026-02-18 18:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('logistics', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drivers', to='users.tenant'),
        ),
        migrations.AddField(
            model_name='driver',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='users.tenant'),
        ),
        migrations.AddField(
            model_name='exception',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_exceptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='exception',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exceptions', to='users.tenant'),
        ),
        migrations.AddField(
            model_name='order',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='users.tenant'),
        ),
        migrations.AddField(
            model_name='exception',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exceptions', to='logistics.order'),
        ),
        migrations.AddField(
            model_name='outboxmessage',
            name='event',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='outbox', to='logistics.event'),
        ),
        migrations.AddField(
            model_name='pod',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pod', to='logistics.order'),
        ),
        migrations.AddField(
            model_name='route',
            name='driver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='routes', to='logistics.driver'),
        ),
        migrations.AddField(
            model_name='route',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routes', to='users.tenant'),
        ),
        migrations.AddField(
            model_name='order',
            name='assigned_route',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='logistics.route'),
        ),
        migrations.AddField(
            model_name='statushistory',
            name='actor_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='statushistory',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='logistics.order'),
        ),
        migrations.AddField(
            model_name='statushistory',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_histories', to='users.tenant'),
        ),
        migrations.AddField(
            model_name='stop',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='logistics.order'),
        ),
        migrations.AddField(
            model_name='statushistory',
            name='stop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='logistics.stop'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='users.tenant'),
        ),
        migrations.AddField(
            model_name='route',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='routes', to='logistics.vehicle'),
        ),
        migrations.AlterUniqueTogether(
            name='order',
            unique_together={('tenant', 'reference_code')},
        ),
        migrations.AlterUniqueTogether(
            name='vehicle',
            unique_together={('tenant', 'plate_number')},
        ),
    ]
